### ISSUE TITLE
师傅是这样用的吗?为什么会报错

### ISSUE THREAD

**Issue by dobatech** [zan8in/afrog#7]
─$ /home/kali/Desktop/afrog_linux_amd64 -T /home/kali/Desktop/vulmap-0.9/list.txt -o afrog_result1.html                                                                                                                               2 ⨯
一个挖洞工具 A tool for finding vulnerabilities - V1.2.7
Default Conf  /home/kali/.config/afrog/afrog-config.yaml
Default Pocs  /home/kali/afrog-pocs v0.1.0
Output Report afrog_result1.html
2/926 | 0% panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa57b41]

goroutine 55 [running]:
github.com/zan8in/afrog/pkg/core.(*Engine).ReleaseChecker(0xc0003480f0, 0xc0003418c0)
        C:/Users/zanbi/go/src/github.com/zan8in/afrog/pkg/core/engine.go:32 +0x21
github.com/zan8in/afrog/pkg/core.(*Engine).executeExpression(_, {_, _}, {{0xc000356ec0, 0x1c}, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...})
        C:/Users/zanbi/go/src/github.com/zan8in/afrog/pkg/core/excute.go:74 +0x1b2
github.com/zan8in/afrog/pkg/core.(*Engine).executeTargets.func2({_, _}, {{0xc000356ec0, 0x1c}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
        C:/Users/zanbi/go/src/github.com/zan8in/afrog/pkg/core/excute.go:62 +0xc5
created by github.com/zan8in/afrog/pkg/core.(*Engine).executeTargets
        C:/Users/zanbi/go/src/github.com/zan8in/afrog/pkg/core/excute.go:59 +0x392

**Comment by zan8in** [comment]
你好，可能是URL不规范造成，明天我复现，修复此Bug

**Comment by zan8in** [comment]
@dobatech 麻烦你加入交流群，沟通一下报错问题
https://github.com/zan8in/afrog#%E4%BA%A4%E6%B5%81%E7%BE%A4

**Comment by zan8in** [comment]
已发布新版本Ｖ1.2.8修复该BUG

**Comment by dobatech** [comment]
好的谢谢师傅了
